coffeedapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from core import urls as core_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include(core_urls)),
]

core/urls.py
from django.conf.urls import include, url
import core.views as coreviews
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', coreviews.LandingView.as_view()),
    url(r'^location/$', coreviews.LocationListView.as_view()),
    url(r'^search/$', coreviews.SearchListView.as_view()),
    url(r'^location/(?P<pk>\d+)/detail/$', coreviews.LocationDetailView.as_view(), name='location_list'),

    url(r'^location/create/$', login_required(coreviews.LocationCreateView.as_view())),
    url(r'^location/(?P<pk>\d+)/update/$', login_required(coreviews.LocationUpdateView.as_view()), name='location_update'),
    url(r'^location/(?P<pk>\d+)/review/create/$', login_required(coreviews.ReviewCreateView.as_view()), name='review_create'),
    url(r'^location/(?P<pk>\d+)/review/update/$', login_required(coreviews.ReviewUpdateView.as_view()), name='review_update'),

    url(r'^entrance/$', coreviews.entrance),



]

core/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models import Avg
from geoposition.fields import GeopositionField
from django.core.validators import RegexValidator

import os
import uuid

RATING_CHOICES = (
    (0, 'None'), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****'),
)
YESNO_CHOICES = (
    (0, 'No'), (1, 'Yes'),
)
PLURAL_CHOICES = (
    (0, 'None'), (1, 'Minimal'), (2, 'Some'), (3, 'Ample'),
)

WIFI_CHOICES = (
    (0, 'None'), (1, 'Spotty'), (2, 'Strong'),
)

COFFEE_CHOICES = (
    (0, 'None'), (1, 'Truck Stop'), (2, 'Good'), (3, 'Really Good'), (4, 'Great'),
)


def upload_to_location(instance, filename):
    blocks = filename.split('.')
    ext = blocks[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    instance.title = blocks[0]
    return os.path.join('uploads/', filename)

# Create your models here.
class Location(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    position = GeopositionField(null=True, blank=True)
    hours = models.TextField(null=True, blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone = models.CharField(validators=[phone_regex], blank=True, max_length=20) # validators should be a list
    website = models.URLField(max_length=500, null=True, blank=True)
    image_file = models.ImageField(upload_to=upload_to_location, null=True, blank=True)

    wifi = models.IntegerField(choices=WIFI_CHOICES, null=True, blank=True)
    seating_cap = models.IntegerField(choices=PLURAL_CHOICES, null=True, blank=True)
    outlets = models.IntegerField(choices=PLURAL_CHOICES, null=True, blank=True)
    bathrooms = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    coffee_quality = models.IntegerField(choices=COFFEE_CHOICES, null=True, blank=True)
    alcohol = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    outdoor_seating = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    food = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)


    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(viewname='location_list', args=[self.id])

    def get_average_rating(self):
        average = self.review_set.all().aggregate(Avg('rating'))['rating__avg']
        if average == None:
            return average
        else:
            return int(average)

    def get_reviews(self):
        return self.review_set.all()


class Review(models.Model):
    location = models.ForeignKey(Location)
    user = models.ForeignKey(User)
    description = models.TextField(null=True, blank=True)
    rating = models.IntegerField(choices=RATING_CHOICES, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from sitegate.decorators import redirect_signedin, sitegate_view
import core.models as coremodels

class LandingView(TemplateView):
    template_name = "base/index.html"

class LocationListView(ListView):
    model = coremodels.Location
    template_name = 'location/list.html'
    paginate_by = 5

class SearchListView(LocationListView):

    def get_queryset(self):
        incoming_query_string = self.request.GET.get('query','')
        return coremodels.Location.objects.filter(title__icontains=incoming_query_string)

class LocationDetailView(DetailView):
    model = coremodels.Location
    template_name = 'location/detail.html'
    context_object_name = 'location'

    def get_context_data(self, **kwargs):
        context = super(LocationDetailView, self).get_context_data(**kwargs)
        location = coremodels.Location.objects.get(id=self.kwargs['pk'])
        if self.request.user.is_authenticated():
            user_reviews = coremodels.Review.objects.filter(location=location, user=self.request.user)
            if user_reviews.count() > 0:
                context['user_review'] = user_reviews[0]
            else:
                context['user_review'] = None
        return context

class LocationCreateView(CreateView):
    model = coremodels.Location
    template_name = 'base/form.html'
    fields = '__all__'

class LocationUpdateView(UpdateView):
    model = coremodels.Location
    template_name = 'base/form.html'
    fields = '__all__'

class ReviewCreateView(CreateView):
    model = coremodels.Review
    template_name = 'base/form.html'
    fields =['description', 'rating']

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.location = coremodels.Location.objects.get(id=self.kwargs['pk'])
        return super(ReviewCreateView, self).form_valid(form)

    def get_success_url(self):
        return self.object.location.get_absolute_url()


class ReviewUpdateView(UpdateView):
    model = coremodels.Review
    template_name = 'base/form.html'
    fields =['description', 'rating']

    def get_object(self):
        return coremodels.Review.objects.get(location__id=self.kwargs['pk'], user=self.request.user)


    def get_success_url(self):
        return self.object.location.get_absolute_url()


@sitegate_view(widget_attrs={'class': 'form-control', 'placeholder': lambda f: f.label}, template='form_bootstrap3') # This also prevents logged in users from accessing our sign in/sign up page.
def entrance(request):
    return render(request, 'base/entrance.html', {'title': 'Sign in & Sign up'})

templates/base/entrance.html
{% extends 'base/theme.html' %}
{% load sitegate %}

{% block main_content %}
    <section id="services">
         <div class="container">
            <div class="row ">
                <div class="col-lg-6 text-center">
                    <div class="my_signin_block">
                        <h2 class="section-heading"><a href="{{ location.get_absolute_url }}">Sign In</a></h2>
                        <h3 class="section-subheading text-muted">Welcome back!</h3>
                        {% sitegate_signin_form %}
                    </div>
                </div>
                <br>
                <div class="col-lg-6 text-center">
                    <div class="my_signup_block">
                        <h2 class="section-heading"><a href="{{ location.get_absolute_url }}">Join Yelp Knockoff</a></h2>
                        <h3 class="section-subheading text-muted">Visit exotic places, and talk smack about them!</h3>
                        {% sitegate_signup_form %}
                    </div>
                </div>
            </div>
         </div>
    </section>
{% endblock %}

templates/base/form.html
{% extends "base/theme.html" %}
{% load widget_tweaks %}
{% block main_content %}

<div class="header-buffer"> </div>

<section id="services">
     <div class="container">
        <div class="row">
            {% if form %}
                <div class="col-md-12">
                    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}{{ form.media }}
                    {% for field in form %}
                        <div class="form-group warning">
                             <label for="exampleInputFile">{{ field.label }}</label>
                             {{ field|add_class:"form-control"}}
                                {% if field.help_text %}<p class="help-block">{{ field.help_text }}</p>{% endif %}
                        </div>
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger" id="error_{{ field.name }}">{{ error|escape }}</div>
                            {% endfor %}
                        {% endif %}

                    {% endfor %}
                    <input type="submit" class="btn btn-success" role="button" value="{{ verb|default:"Submit" }}" />
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

templates/base/index.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>C O F F E E D</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/agency.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>


</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="/">C O F F E E D</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    {% block navigation %}
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">How It Works</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#team">Our Team</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Get Invited</a>
                    </li>
                    {% endblock %}
                </ul>
                {%  block search %}
                {% endblock %}
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    {% block main_content %}

    <!-- Header -->
    <header>
        <div class="container">
            <div class="intro-text">
                <div class="intro-heading">Hi, We're Coffeed.</div>
                <div class="intro-lead-in">Find your favorite office away from home. We're curating some of the best coffee shops to successfully work, meet & thrive at.</div>
                <a href="#services" class="page-scroll btn btn-xl">How It Works</a>
            </div>
        </div>
    </header>

    <!-- Services Section -->
    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">How It Works</h2>
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-4">
                    <img class='coffeed-svg-icon' src="{% static 'img/svg/python_flag.svg' %}"/>
                    <h4 class="service-heading">Discover Amazing Spots</h4>
                    <p class="text-muted">Coffeed works hard to curate the best coffee places for independent working- so that you can hit those deadlines.</p>
                </div>
                <div class="col-md-4">
                    <img class='coffeed-svg-icon' src="{% static 'img/svg/python_badge.svg' %}"/>
                    <h4 class="service-heading">Review Your Favorites</h4>
                    <p class="text-muted">Find out what other people are saying and chime in with your opinion. Help each other find the best work locale.</p>
                </div>
                <div class="col-md-4">
                    <img class='coffeed-svg-icon' src="{% static 'img/svg/python_rocket.svg' %}"/>
                    <h4 class="service-heading">Promote Your Business</h4>
                    <p class="text-muted">Anyone can add their coffee shop location to Coffeed for free. Sit back, relax & watch the reviews pour in.</p>
                </div>
            </div>
        </div>
    </section>



    <!-- Team Section -->
    <section id="team" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Our Caffeinated Team</h2>
                    <h3 class="section-subheading text-muted">Working hard to find you the best of the best.</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="team-member">
                        <img src="{% static 'img/team/1.jpg' %}" class="img-responsive img-circle" alt="">
                        <h4>Kristina Zmaic</h4>
                        <p class="text-muted">Founder & Designer</p>
                        <ul class="list-inline social-buttons">
                            <li><a href="https://twitter.com/kzmaic"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="https://instagram.com/kzmaic/"><i class="fa fa-instagram"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="team-member">
                        <img src="{% static 'img/team/2.jpg' %}" class="img-responsive img-circle" alt="">
                        <h4>Eric Neuman</h4>
                        <p class="text-muted">Web & Business Development</p>
                        <ul class="list-inline social-buttons">
                            <li><a href="https://twitter.com/eric_neuman"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="https://instagram.com/eric_neuman"><i class="fa fa-instagram"></i></a>
                            </li>
                            <li><a href="https://www.linkedin.com/in/ericneuman"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="team-member">
                        <img src="{% static 'img/team/3.jpg' %}" class="img-responsive img-circle" alt="">
                        <h4>Chris Castiglione</h4>
                        <p class="text-muted">Project Management</p>
                        <ul class="list-inline social-buttons">
                            <li><a href="https://twitter.com/castig"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="https://instagram.com/castig"><i class="fa fa-instagram"></i></a>
                            </li>
                            <li><a href="http://www.linkedin.com/in/castig"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <p class="large text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Clients Aside -->
    <aside class="clients">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <a href="#">
                        <img src="{% static 'img/logos/envato.jpg' %}" class="img-responsive img-centered" alt="">
                    </a>
                </div>
                <div class="col-md-3 col-sm-6">
                    <a href="#">
                        <img src="{% static 'img/logos/designmodo.jpg' %}" class="img-responsive img-centered" alt="">
                    </a>
                </div>
                <div class="col-md-3 col-sm-6">
                    <a href="#">
                        <img src="{% static 'img/logos/themeforest.jpg' %}" class="img-responsive img-centered" alt="">
                    </a>
                </div>
                <div class="col-md-3 col-sm-6">
                    <a href="#">
                        <img src="{% static 'img/logos/creative-market.jpg' %}" class="img-responsive img-centered" alt="">
                    </a>
                </div>
            </div>
        </div>
    </aside>

    <!-- Contact Section -->
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="section-heading">Be the first to find out.</h2>
                    <h3 class="section-subheading text-muted">We'll be launching soon, so sign up to be one of the first to be invited.</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                <div id="mc_embed_signup">
                    <form action="//onemonth.us7.list-manage.com/subscribe/post?u=0906b75c0e799fc3ea1dbf935&amp;id=612428ba89" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                        <div class="form-group">
                            <input type="email" value="" name="EMAIL" class="email form-control" id="mce-EMAIL" placeholder="email address" required style="width: 300px;">
                        </div>
                        <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary">
                    </form>
                </div>
                </div>
            </div>
        </div>
    </section>

    {% endblock %}

    <footer>
        <div class="container">
            {% block pagination %}
            {% endblock %}
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Your Website 2014</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="https://twitter.com/getcoffeed"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="https://www.facebook.com/getcoffeed"><i class="fa fa-facebook"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Maps JavaScript -->
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="{% static 'js/gmaps.js' %}"></script>
    <script src="{% static 'js/maps.js' %}"></script>

    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{% static 'js/agency.js' %}"></script>


</body>

</html>

templates/base/rating.html
<div class="coffeed-rating">
{% if rating == 1 %}
    <i class="fa fa-heart"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% elif rating == 2 %}
    <i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% elif rating == 3 %}
    <i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% elif rating == 4 %}
    <i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart-o"></i>
{% elif rating == 5 %}
    <i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i>
{% else %}
    <i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% endif %}
</div>

templates/base/reviews.html
<div class="row">
    <div class="col-md-8">
        <h2>{{ review.user.get_full_name }} <a class="subheading"> | {{ review.created_at | date }}</a></h2>
    </div>
    <div class="col-md-4 text-right">
        <h2>{% include 'base/rating.html' with rating=review.rating %}</h2>
    </div>
</div>
<p>{{ review.description }}</p>

templates/base/theme.html
{% extends 'base/index.html' %}

{% block navigation %}
     <li> <a class="page-scroll" href="/location">Find a Coffee Shop</a> </li>
     {% if user.is_authenticated %}
     <li> <a class="page-scroll" href="/location/create">Add a Location</a> </li>
     {% else %}
     <li> <a class="page-scroll" href="/entrance">Login</a> </li>
     {% endif %}


{% endblock %}

{% block search %}
     <form action="/search/" class="navbar-form navbar-right" method="get">
          <div class="form-group">
               <input type="text" placeholder="Search" class="form-control" name="query"></input>
          </div>
     </form>
{% endblock %}

{% block main_content %}

{% endblock %}

templates/location/detail.html
<!DOCTYPE html>
    {% extends 'base/theme.html' %}

    {% block main_content %}
    <div class="row main-content">
        <div class="col-md-2"></div>

        <div class="col-md-8">

            <div class="row">
                <div class="col-md-8">
                    <h3><a href="{{ location.get_absolute_url }}">{{ location.title }}</h3></a></h3>
                </div>
                <div class="col-md-4 text-right">
                    <h3>{% include 'base/rating.html' with rating=location.get_average_rating %}</h3>
                </div>

                <div class="data-layer">
                        <p class="location-data" data-latitude="{{ location.position.latitude }}" data-longitude="{{ location.position.longitude }}" data-id="{{ location.id }}">{{ location.title }}</p>
                </div>
                <div class="col-md-4 panel">
                    <div class="wide-map short-map" id="map"></div>
                    <div class="col-md-3"></div>
                    <div class="col-md-6 text-center">
                    <br>
                         {% if location.address %}<p>{{ location.address }}</p>{% endif %}
                         {% if location.phone %}<p>{{ location.phone }}</p>{% endif %}
                         {% if location.website %}<p><a href="{{ location.website }}">{{ location.website }}</a></p>{% endif %}
                    </div>
                    <div class="col-md-3"></div>
                 </div>

                <div class="col-md-12">
                    {% if location.address %} <p> <strong>Location:</strong> {{ location.address }} </p> {% endif %}
                    {% if location.hours %} <p>Open: {{ location.hours }} </p> {% endif %}
                    {% include 'location/specifics.html' with location=location %}
                    {% if location.description %} <p> {{ location.description }} </p> {% endif %}
                    {% if location.image_file %} <img class="img-responsive" src="{{ location.image_file.url }}" /> {% endif %}
                </div>
                <div class="col-md-12">
                    <a type="button" href="{% url 'location_update' pk=location.id %}" class="btn btn-default pull-right">Edit</a>
                    {% if user_review %}
                    <a type="button" href="{% url 'review_update' pk=location.id %}" class="btn btn-default pull-right">Update Review</a>
                    {% else %}
                    <a type="button" href="{% url 'review_create' pk=location.id %}" class="btn btn-default pull-right">Create Review</a>
                    {% endif %}
                </div>

            <div class="col-md-12">
                {% for review in location.get_reviews %}
                    {% include 'base/reviews.html' with location=location %}
                {% endfor %}
            </div>
            </div>
        </div>

        <div class="col-md-2"></div>


    </div>
    {% endblock %}

templates/location/list.html
<!DOCTYPE html>
    {% extends 'base/theme.html' %}
    {% load bootstrap_pagination %}

    {% block main_content %}
    <!-- Getting Lat/Long Data via gmaps -->
    <div class="data-layer">
        <ul>
        {% for location in object_list %}
            <li class="location-data" data-latitude="{{ location.position.latitude }}" data-longitude="{{ location.position.longitude }}" data-id="{{ location.id }}">{{ location.title }}</li>
        {% endfor %}
        </ul>
    </div>
    <div id="map" class="wide-map"></div>

    <div class="row main-content">
        <div class="col-md-2"></div>

        <div class="col-md-8">

            {% for location in object_list %}
            <div class="row">
                <div class="col-md-8">
                    <h3><a href="{{ location.get_absolute_url }}">{{ location.title }}</a></h3>
                </div>
                <div class="col-md-4 text-right">
                    <h3>{% include 'base/rating.html' with rating=location.get_average_rating %}</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    {% if location.address %}<p><b>Location: </b>{{ location.address }}</p>{% endif %}
                    {% if location.hours %}<p>{{ location.hours }}</p>{% endif %}
                    {% if location.image_file %}<img src="{{ location.image_file.url }}"></img>{% endif %}
                    {% include 'location/specifics.html' with location=location %}
                    <p>{{ location.description }}</p>

                </div>
            </div>
            {% endfor %}

        </div>

        <div class="col-md-2"></div>
    </div>
    {% endblock %}

    {% block pagination %}
        {% bootstrap_paginate page_obj range=10 show_prev_next='false' show_first_last='true' %}
    {% endblock %}

templates/location/specifics.html
<div class="row">
    <div class="col-md-6">
        <div><b>Wifi: </b>{% if location.wifi %}{{ location.get_wifi_display }}{% else %}----{% endif %}</div><br/>
        <div><b>Seating: </b>{% if location.seating_cap %}{{ location.get_seating_cap_display }}{% else %}----{% endif %}</div><br/>
        <div><b>Outlets: </b>{% if location.outlets %}{{ location.get_outlets_display }}{% else %}----{% endif %}</div><br/>
        <div><b>Bathrooms: </b>{% if location.bathrooms %}{{ location.get_bathrooms_display }}{% else %}----{% endif %}</div><br/>
    </div>
    <div class="col-md-6">
        <div><b>Coffee: </b>{% if location.coffee_quality %}{{ location.get_coffee_quality_display }}{% else %}----{% endif %}</div><br/>
        <div><b>Alcohol: </b>{% if location.alcohol %}{{ location.get_alcohol_display }}{% else %}----{% endif %}</div><br/>
        <div><b>Outdoor Seating: </b>{% if location.outdoor_seating %}{{ location.get_outdoor_seating_display }}{% else %}----{% endif %}</div><br/>
        <div><b>Food: </b>{% if location.food %}{{ location.get_food_display }}{% else %}----{% endif %}</div><br/>
    </div>
</div>